name: Practice code

on:
  push:


jobs:
  check_verisons:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout repository 1
      #   uses: actions/checkout@v1
      
      # - name: Checkout repository 2
      #   uses: actions/checkout@v2
      
      # - name: Checkout repository 3
      #   uses: actions/checkout@v3
      
      # - name: Checkout repository 4
      #   uses: actions/checkout@v4
      
      - name: Checkout repository 6
        uses: actions/checkout@v7

  multiple-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Multiple command
        run: |
          echo "Date and time is:"
          date
          echo "who is present"

          whoami


